### ISSUE TITLE
Thank you for the library, ok to use in a free project?

### ISSUE THREAD

**Issue by jzohrab** [buruzaemon/natto-py#125]
Hello, thanks for making this available.  I tried it out and it works great on my Mac.

I'm rewriting a free public app -- [Lute](https://github.com/jzohrab/lute) for language learning -- from PHP to Python, and need something to work with MeCab like you have here.  The repo for Lute v3 is [here](https://github.com/jzohrab/lute_v3).  A few questions:

* is it problematic for me to use this in the Lute app?  Lute's free, open source, etc etc.
* do you foresee any future work on this library, are you still maintaining it?  If not, any other suggestions?  This library acts as a wrapper around a locally installed MeCab (i.e., they install MeCab and make sure it's on their path), which is what I'm looking for.
* the readme says that this should work for win/mac/nix, do you still feel good about that?  I've only tested it on my machine, but each user's machine is different  :-(

Cheers and thank you again,
Jeff

**Comment by buruzaemon** [comment]
Hello, @jzohrab and thanks for reaching out to me.

I apologize for the tardiness in replying, I do not actively support natto-py much nowadays as development of the underlying MeCab itself has stopped for several years now.

To answer your questions...

> is it problematic for me to use this in the Lute app? Lute's free, open source, etc etc.
Not at all. If you look at the BSD 2-Clause "Simplified" [LICENSE](https://github.com/buruzaemon/natto-py/blob/master/LICENSE) I use, it is quite liberal. As long as you follow that, you are free to use natto-py in Lute.

> do you foresee any future work on this library, are you still maintaining it?
Barring any glaring bugs discovered, I do not think I will be developing this project any further.

> the readme says that this should work for win/mac/nix, do you still feel good about that?
Windows is always problematic, since I think the end-user will have to build MeCab for 64-bit by themselves, which can be tricky. MeCab has all kinds of options when building, but if the end-user is aware of what they are doing, then they should be able to configure natto-py to work. Linux has never really been a problem, and likewise for Mac. 

Lute sounds interesting, I wish you all the best as you re-write that!

**Comment by jzohrab** [comment]
Thank you very much, I'll go forward with natto-py for now, and see how it works.  For the mac, it's great -- too bad Windows is so rough.  Lute requires those users to install mecab on their own and get it into their PATH anyway, so there's always going to be problems for them.  Ah well, can't win sometimes.  If things totally bomb I'll just have them configure some kind of system call.  :-)

Yeah MeCab seems stopped, which is funny because it seems so popular and used among learners.

Thanks again!
